const FETCH_USERS_DATA = "FETCH_USERS_DATA";
const FETCH_USERS_DATA_SUCCESS = "FETCH_USERS_DATA_SUCCESS";
const FETCH_USERS_DATA_ERROR = "FETCH_USERS_DATA_ERROR";

const DELETE_USER = "DELETE_USER";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const DELETE_USER_ERROR = "DELETE_USER_ERROR";

const UPDATE_USER = "UPDATE_USER";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

const CREATE_USER = "CREATE_USER";
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
const CREATE_USER_ERROR = "CREATE_USER_ERROR";

const SET_EDIT_ROW = "SET_EDIT_ROW";
const SET_CREATE_USER_ROW = "SET_CREATE_USER_ROW";

const Types = {
  FETCH_USERS_DATA,
  FETCH_USERS_DATA_SUCCESS,
  FETCH_USERS_DATA_ERROR,

  DELETE_USER,
  DELETE_USER_SUCCESS,
  DELETE_USER_ERROR,

  UPDATE_USER,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,

  CREATE_USER,
  CREATE_USER_SUCCESS,
  CREATE_USER_ERROR,

  SET_EDIT_ROW,
  SET_CREATE_USER_ROW,
};

export default Types;
