const Types = {
  FETCH_USERS_DATA: "FETCH_USERS_DATA",
  FETCH_USERS_DATA_SUCCESS: "FETCH_USERS_DATA_SUCCESS",
  FETCH_USERS_DATA_ERROR: "FETCH_USERS_DATA_ERROR",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",

  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",

  SET_EDIT_ROW: "SET_EDIT_ROW",
  SET_CREATE_USER_ROW: "SET_CREATE_USER_ROW",
};

export default Types;
